@startuml password
actor "User"
participant "Client Application" as CA
participant "Authorization Server" as AS
participant "Resource Server" as RS

"User" -> CA
CA -> AS
AS -> AS
AS -> CA
CA -> RS
RS -> RS
RS -> CA
@enduml